# Generated by Django 3.0.5 on 2020-04-27 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 9, 8, 58, 812115, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
